module.exports = {
    MODE: "tdm",
    BLOCKADE_LOOP: true,
    TEAMS: 2,
    WIDTH: 5500,
    HEIGHT: 5500,
    X_GRID: 17,
    Y_GRID: 17,
    ROOM_SETUP: [
        [ "wall", "wall", "wall", "wall", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "wall", "wall", "wall" ],
        [ "wall", "bas1", "bap1", "bas1", "bas1", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "bas2", "bas2", "bap2", "bas2", "wall" ],
        [ "wall", "norm", "bas1", "norm", "norm", "wall", "norm", "nest", "nest", "nest", "norm", "wall", "norm", "norm", "bas2", "norm", "wall" ],
        [ "wall", "norm", "bas1", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "bas2", "norm", "wall" ],
        [ "wall", "norm", "wall", "wall", "wall", "wall", "norm", "nest", "nest", "nest", "norm", "wall", "wall", "wall", "wall", "norm", "wall" ],
        [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
        [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
        [ "norm", "norm", "norm", "norm", "wav1", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "wav2", "norm", "norm", "norm", "norm" ],
        [ "norm", "norm", "dom1", "norm", "wav1", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "wav2", "norm", "dom2", "norm", "norm" ],
        [ "norm", "norm", "norm", "norm", "wav1", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "wav2", "norm", "norm", "norm", "norm" ],
        [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
        [ "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm" ],
        [ "wall", "norm", "wall", "wall", "wall", "wall", "norm", "nest", "nest", "nest", "norm", "wall", "wall", "wall", "wall", "norm", "wall" ],
        [ "wall", "norm", "bas1", "norm", "norm", "norm", "norm", "nest", "nest", "nest", "norm", "norm", "norm", "norm", "bas2", "norm", "wall" ],
        [ "wall", "norm", "bas1", "norm", "norm", "wall", "norm", "nest", "nest", "nest", "norm", "wall", "norm", "norm", "bas2", "norm", "wall" ],
        [ "wall", "bas1", "bap1", "bas1", "bas1", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "bas2", "bas2", "bap2", "bas2", "wall" ],
        [ "wall", "wall", "wall", "wall", "wall", "wall", "norm", "norm", "norm", "norm", "norm", "wall", "wall", "wall", "wall", "wall", "wall" ]
    ],
    BOT_XP: 500,
};