module.exports = {
    WIDTH: 5500,
    HEIGHT: 5500,
    X_GRID: 21,
    Y_GRID: 21,
    ROOM_SETUP: [
        ["outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb"],
        ["outb", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "bas1", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "bas1", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "bas1", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "nest", "norm", "norm", "bas1", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "outb", "outb", "outb", "boss", "boss", "boss", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "norm", "wall", "outb"],
        ["outb", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "wall", "outb"],
        ["outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb", "outb"],
    ],
};